import {build} from 'esbuild';
import {dirname,join} from 'node:path';
import {readFile,writeFile,mkdir,readdir,cp} from 'node:fs/promises';
const result=await build({entryPoints:['src/main.js'],bundle:true,format:'iife',minify:true,write:false,target:['es2020'],legalComments:'eof'});
const template=await readFile('src/index.html','utf8'),css=await readFile('src/style.css','utf8'),script=result.outputFiles[0].text.replace(/\t/g,'  ').replace(/[ \t]+$/gm,'');
const image=async p=>'data:image/png;base64,'+(await readFile(p)).toString('base64');
const embedded={},hosted={};async function walk(dir){for(const file of await readdir(dir,{withFileTypes:true})){const p=dir+'/'+file.name;if(file.isDirectory())await walk(p);else if(/\.(png|jpg|jpeg|webp|hdr|woff2|bin|gltf)$/.test(file.name)){const ext=file.name.split('.').pop(),mime={png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',hdr:'application/octet-stream',woff2:'font/woff2',bin:'application/octet-stream',gltf:'model/gltf+json'}[ext];embedded[p]='data:'+mime+';base64,'+(await readFile(p)).toString('base64');hosted[p]=p;}}}await walk('assets/materials');await walk('assets/models');await walk('assets/fonts');for(const path of Object.keys(embedded).filter(p=>p.endsWith('.gltf'))){const data=JSON.parse(await readFile(path,'utf8'));for(const ref of [...(data.buffers||[]),...(data.images||[])]){if(ref.uri){const key=join(dirname(path),ref.uri);if(!embedded[key])throw new Error('Missing model dependency '+key);ref.uri=embedded[key];}}embedded[path]=data;}
for(const path of Object.keys(embedded)){if((path.startsWith('assets/models/')&&!path.endsWith('.gltf'))||path.endsWith('kloofendal_48d_partly_cloudy_2k.hdr'))delete embedded[path];}
let offlineCss=css;for(const [path,url]of Object.entries(embedded)){if(path.startsWith('assets/fonts/'))offlineCss=offlineCss.replaceAll(path,url);}
const inline=template.replace('/*ASSET_URLS*/',()=>JSON.stringify(embedded)).replace('/*STYLE*/',offlineCss).replace('/*SCRIPT*/',()=>script.replaceAll('</script','<\\/script')).replaceAll('__PLAN_IMAGE__',await image('assets/floor-plan.png')).replaceAll('__INTERIOR_IMAGE__',await image('assets/interior-reference.png')).replaceAll('__BUILDING_IMAGE__',await image('assets/building-reference.png')).replaceAll('__LOCATION_IMAGE__',await image('assets/location-reference.png'));
const web=template.replace('/*ASSET_URLS*/',()=>JSON.stringify(hosted)).replace('<style>/*STYLE*/</style>','<link rel="stylesheet" href="style.css">').replace('<script>/*SCRIPT*/</script>','<script src="app.js" defer></script>').replaceAll('__PLAN_IMAGE__','assets/floor-plan.png').replaceAll('__INTERIOR_IMAGE__','assets/interior-reference.png').replaceAll('__BUILDING_IMAGE__','assets/building-reference.png').replaceAll('__LOCATION_IMAGE__','assets/location-reference.png');
await mkdir('dist',{recursive:true});await cp('assets','dist/assets',{recursive:true});await writeFile('dist/index.html',web);await writeFile('dist/style.css',css);await writeFile('dist/app.js',script.replaceAll('__PLAN_IMAGE__','assets/floor-plan.png').replaceAll('__INTERIOR_IMAGE__','assets/interior-reference.png').replaceAll('__BUILDING_IMAGE__','assets/building-reference.png').replaceAll('__LOCATION_IMAGE__','assets/location-reference.png'));await writeFile('My Home 3D.html',inline);
console.log('Built hosted assets and standalone browser model: '+(inline.length/1024/1024).toFixed(2)+' MB embedded');
