import {chromium} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=gl']});
const folder=process.argv[2]||'artifacts/realism-v1';await mkdir(folder,{recursive:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')console.log(m.type(),m.text().slice(0,300));});
try{await page.goto('http://127.0.0.1:4173',{waitUntil:'domcontentloaded',timeout:60000});await page.waitForFunction(()=>!!window.__home,{timeout:90000});await page.waitForSelector('#loading',{state:'detached'});await page.waitForTimeout(1200);await page.screenshot({path:folder+'/overview.png'});console.log('overview captured');await page.click('[data-view="plan"]');await page.waitForTimeout(1500);await page.screenshot({path:folder+'/plan.png'});
for(const id of ['living','kitchen','bed2','master','bed3','baths','balconies']){await page.click(`[data-room="${id}"]`);await page.click('[data-view="walk"]');await page.waitForTimeout(600);await page.screenshot({path:folder+'/'+id+'-day.png'});console.log(id,'captured');if(id==='living'||id==='master'||id==='baths'){await page.click('[data-light="evening"]');await page.waitForTimeout(400);await page.screenshot({path:folder+'/'+id+'-evening.png'});await page.click('[data-light="day"]');}}
for(const [name,space,variant] of [['bathroom-02','baths','Bathroom 02'],['master-bath','baths','Master bathroom'],['bedroom-balcony','balconies','Bedroom balcony']]){await page.click(`[data-room="${space}"]`);await page.getByRole('button',{name:variant,exact:true}).click();await page.waitForTimeout(300);await page.screenshot({path:folder+'/'+name+'-day.png'});}await page.click('#reset');await page.waitForTimeout(1300);await page.setViewportSize({width:390,height:844});await page.waitForTimeout(600);await page.screenshot({path:folder+'/mobile.png'});await writeFile(folder+'/report.json',JSON.stringify({errors,details:await page.evaluate(()=>({sections:window.__home.architecturalView.sections.length,meshes:window.__home.renderer.info.render.calls,photoSupported:window.__home.photo.supported,stats:window.__home.interior.stats,starts:window.__home.rooms.map(r=>({id:r.id,canWalk:window.__home.canWalk(...r.walk)}))}))},null,2));console.log('DONE',errors);
}finally{await browser.close();}
