import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=vulkan','--enable-features=Vulkan','--disable-vulkan-surface']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,300));});await mkdir('artifacts/validation',{recursive:true});
try{await page.goto('http://127.0.0.1:4173',{waitUntil:'domcontentloaded',timeout:60000});await page.waitForFunction(()=>!!window.__home,null,{timeout:90000});await page.waitForSelector('#loading',{state:'detached'});await page.click('#my-apartment');assert.equal(await page.locator('.room-btn').count(),7);assert.ok(await page.evaluate(()=>window.__home.rooms.every(r=>window.__home.canWalk(...r.walk))));
await page.click('[data-view="walk"]');await page.waitForFunction(()=>window.__home.architecturalView.ceilings.visible,null,{timeout:15000});assert.equal(await page.evaluate(()=>window.__home.architecturalView.ceilings.visible),true);await page.click('[data-room="baths"]');for(const name of ['Bathroom 01','Bathroom 02','Master bathroom']){await page.getByRole('button',{name,exact:true}).click();assert.ok(await page.evaluate(()=>window.__home.canWalk(window.__home.camera.position.x,window.__home.camera.position.z)));}await page.click('[data-room="balconies"]');await page.getByRole('button',{name:'Bedroom balcony',exact:true}).click();assert.ok(await page.evaluate(()=>window.__home.canWalk(window.__home.camera.position.x,window.__home.camera.position.z)));await page.keyboard.press('Escape');await page.waitForTimeout(1100);assert.equal(await page.evaluate(()=>window.__home.architecturalView.ceilings.visible),false);const caps=await page.evaluate(()=>window.__home.architecturalView.sections.filter(s=>s.mesh.visible&&s.mesh.geometry!==s.original).length);assert.ok(caps>10);
await page.locator('#wall-height').fill('1.5');assert.equal(await page.evaluate(()=>window.__home.wallHeight),1.5);await page.locator('#wall-height').fill('0.75');await page.uncheck('#furniture');assert.equal(await page.evaluate(()=>window.__home.furnitureVisible),false);await page.check('#furniture');
await page.click('#photo-quality');await page.waitForFunction(()=>window.__home.photo.samples>=2||!window.__home.photo.active,{timeout:120000});assert.ok(await page.evaluate(()=>window.__home.photo.active&&window.__home.photo.samples>=2));console.log('Photo quality samples:',await page.evaluate(()=>window.__home.photo.samples));await page.screenshot({path:'artifacts/validation/photo-overview.png'});await page.click('#cancel-photo');assert.equal(await page.evaluate(()=>window.__home.photo.active),false);
await page.click('[data-room="master"]');await page.click('[data-view="walk"]');await page.waitForTimeout(300);await page.click('#photo-quality');await page.waitForFunction(()=>window.__home.photo.samples>=1||!window.__home.photo.active,{timeout:120000});assert.equal(await page.evaluate(()=>window.__home.photo.active),true);await page.keyboard.down('w');await page.waitForTimeout(180);await page.keyboard.up('w');assert.equal(await page.evaluate(()=>window.__home.photo.active),false);await page.keyboard.press('Escape');
await page.click('[data-light="evening"]');assert.equal(await page.evaluate(()=>window.__home.evening),true);assert.ok(await page.evaluate(()=>window.__home.interior.lights.some(l=>l.intensity>0)));await page.click('[data-light="day"]');
await page.click('#reference-btn');assert.ok(await page.locator('#reference').isVisible());await page.click('#close-reference');
const glbPromise=page.waitForEvent('download',{timeout:120000});await page.click('#download-model');const dl=await glbPromise;await dl.saveAs('My Home.glb');const glb=await readFile('My Home.glb');assert.equal(glb.subarray(0,4).toString(),'glTF');assert.ok(glb.length>100000);assert.equal(await page.evaluate(()=>window.__home.wallHeight),.75);
const imagePromise=page.waitForEvent('download');await page.click('#snapshot');await imagePromise;
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);await page.click('#settings-open');assert.ok(await page.locator('#settings').isVisible());await page.click('#settings-close');await page.screenshot({path:'artifacts/validation/mobile.png'});
await page.route('https://**/*',route=>route.abort());await page.goto('file:///home/vikas/3dhouse/My%20Home%203D.html',{waitUntil:'domcontentloaded',timeout:60000});await page.waitForFunction(()=>!!window.__home,null,{timeout:90000});assert.equal(await page.evaluate(()=>window.__home.rooms.length),7);assert.deepEqual(errors,[]);const result={passed:true,caps,glbBytes:glb.length,errors};await writeFile('artifacts/validation/results.json',JSON.stringify(result,null,2));console.log(result);
}finally{await browser.close();}
