import * as THREE from 'three';
import { RenderTarget2DArray } from 'three-gpu-pathtracer/src/uniforms/RenderTarget2DArray.js';
import { FullScreenQuad } from 'three/addons/postprocessing/Pass.js';
import { WebGLPathTracer, DenoiseMaterial, BlurredEnvMapGenerator } from 'three-gpu-pathtracer';

export function createPhotoQuality(renderer,scene,camera,renderInteractive,onStatus) {
 let blurredEnvironment=null,tracer=null,denoise=null,denoiseQuad=null,active=false,generation=0,started=false,lastSample=-1,savedExposure=null,ownedTargets=[];
 let supported=renderer.capabilities.isWebGL2&&renderer.extensions.has('EXT_color_buffer_float');
 function disposeTracer(){if(!tracer)return;for(const pass of [tracer._pathTracer,tracer._lowResPathTracer]){const material=pass?.material;if(!material)continue;for(const [key,uniform]of Object.entries(material.uniforms)){if(['backgroundMap','textures','iesProfiles','sobolTexture'].includes(key))continue;uniform.value?.dispose?.();uniform.value?.tex?.dispose?.();}material.dispose();}for(const target of ownedTargets){target.fsQuad?.material?.dispose();target.dispose();}ownedTargets=[];tracer._lowResPathTracer?.dispose();tracer._internalBackground?.dispose();tracer._colorBackground?.dispose();tracer.dispose();tracer=null;}
 // Keep target ownership until disposeTracer releases the GPU allocations.
 function stop(){if(savedExposure!==null){renderer.toneMappingExposure=savedExposure;savedExposure=null;}generation++;active=false;started=false;if(tracer){tracer.pausePathTracing=true;tracer.reset();}onStatus({active:false,supported,samples:0});}
 async function start(){if(!supported){onStatus({active:false,supported:false,samples:0});return false;}stop();const token=generation;active=true;savedExposure=renderer.toneMappingExposure;renderer.toneMappingExposure=scene.userData.interiorView?(scene.userData.photoRoom?.id==='baths'?2.9:scene.userData.photoRoom?.id==='balconies'?1.2:2.25):1.05;onStatus({active:true,preparing:true,supported,samples:0});await new Promise(r=>requestAnimationFrame(r));try{if(tracer){disposeTracer();denoiseQuad.dispose();denoise.dispose();}if(!tracer){tracer=new WebGLPathTracer(renderer);const material=tracer._pathTracer.material;const maps=new RenderTarget2DArray(1,1),ies=new RenderTarget2DArray(360,180,{type:THREE.HalfFloatType,wrapS:THREE.ClampToEdgeWrapping,wrapT:THREE.ClampToEdgeWrapping});ownedTargets=[maps,ies];material.textures=maps.texture;material.iesProfiles=ies.texture;tracer.bounces=5;tracer.renderScale=.75;tracer.tiles.set(3,3);tracer.minSamples=1;tracer.fadeDuration=0;tracer.rasterizeScene=false;tracer.renderDelay=0;tracer.textureSize.set(1024,1024);tracer.filterGlossyFactor=.5;tracer.rasterizeSceneCallback=renderInteractive;denoise=new DenoiseMaterial({sigma:1.25,kSigma:1.6,threshold:.28});denoiseQuad=new FullScreenQuad(denoise);tracer.renderToCanvasCallback=(target,renderer,quad)=>{if(tracer.samples<12){quad.render(renderer);return;}denoise.map=target.texture;denoise.opacity=quad.material.opacity;denoise.threshold=Math.max(.07,.34/Math.sqrt(tracer.samples/128));denoiseQuad.render(renderer);};}
 // UI dimensions/selection helpers are raster overlays, not physical geometry.
 const helpers=[];const room=scene.userData.photoRoom;if(room&&scene.userData.interiorView){const area=new THREE.Box3(new THREE.Vector3(room.x-.5,-1,room.z-.5),new THREE.Vector3(room.x+room.w+.5,4,room.z+room.d+.5));const furniture=scene.getObjectByName('Furniture');furniture?.traverse(o=>{if(o.isMesh&&o.visible&&!area.intersectsBox(new THREE.Box3().setFromObject(o))){helpers.push(o);o.visible=false;}});}
 scene.traverse(o=>{if(o.visible&&(o.isSprite||o.isLine||o.userData.viewerHelper||(o.isLight&&o.intensity<=.00001))){helpers.push(o);o.visible=false;}});
 const savedBg=scene.background;scene.background=scene.userData.interiorView?scene.environment:new THREE.Color('#e8e8e0');
 const savedEnvironment=scene.environment;try{if(!blurredEnvironment&&savedEnvironment){const generator=new BlurredEnvMapGenerator(renderer);try{blurredEnvironment=generator.generate(savedEnvironment,.13);}finally{generator.copyQuad.material.dispose();generator.dispose();}}if(blurredEnvironment)scene.environment=blurredEnvironment;scene.updateMatrixWorld(true);const photoScene=scene.clone(true);photoScene.traverse(o=>{if(!o.isMesh)return;const materials=Array.isArray(o.material)?o.material:[o.material];const replacements=materials.map(m=>{if(m.userData.photoTransmission===undefined)return m;const physical=m.clone();physical.transmission=m.userData.photoTransmission;physical.opacity=m.userData.photoOpacity;return physical;});o.material=Array.isArray(o.material)?replacements:replacements[0];});photoScene.updateMatrixWorld(true);tracer.setScene(photoScene,camera);}finally{scene.environment=savedEnvironment;helpers.forEach(o=>o.visible=true);scene.background=savedBg;}
 if(token!==generation)return false;tracer.pausePathTracing=false;tracer.reset();started=true;lastSample=-1;return true;
 }catch(e){console.error('Photo quality:',e);stop();onStatus({active:false,supported,error:true,samples:0});return false;}}
 function render(){if(!active||!started){renderInteractive();return;}try{tracer.renderSample();const samples=Math.floor(tracer.samples);if(samples!==lastSample){lastSample=samples;onStatus({active:true,supported,samples,preparing:tracer.isCompiling});}if(samples>=1024)tracer.pausePathTracing=true;}catch(e){console.error('Photo rendering:',e);stop();renderInteractive();onStatus({active:false,supported,error:true,samples:0});}}
 return {start,stop,render,disable(){supported=false;active=false;started=false;generation++;tracer=null;onStatus({active:false,supported:false,samples:0,error:true});},get ready(){return active&&started&&!tracer?.isCompiling;},get active(){return active;},get samples(){return tracer?.samples||0;},get supported(){return supported;},get tracer(){return tracer;}};
}
